//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PardiniService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://hermespardini.com.br/b2b/apoio/schemas", ConfigurationName="PardiniService.XMLServerSoap")]
    public interface XMLServerSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hermespardini.com.br/b2b/apoio/schemas/HPWS.XMLServer.cancelaAmostra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<string> cancelaAmostraAsync(string login, string passwd, string idTuboLab);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hermespardini.com.br/b2b/apoio/schemas/HPWS.XMLServer.cancelaExame", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<string> cancelaExameAsync(string login, string passwd, string codPedApoio, string codExmApoio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hermespardini.com.br/b2b/apoio/schemas/HPWS.XMLServer.getGrupoFracionament" +
            "o", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<string> getGrupoFracionamentoAsync(string login, string passwd, long examesVeterinarios);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hermespardini.com.br/b2b/apoio/schemas/HPWS.XMLServer.getListaErroPedido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RastreabilidadeExame))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RastreabilidadeAmostra))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PendenciaTecnicaExame))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PendenciaTecnicaPedido))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Erro))]
        System.Threading.Tasks.Task<PardiniService.ListaErro> getListaErroPedidoAsync(string login, string passwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hermespardini.com.br/b2b/apoio/schemas/HPWS.XMLServer.getPedido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RastreabilidadeExame))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RastreabilidadeAmostra))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PendenciaTecnicaExame))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PendenciaTecnicaPedido))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Erro))]
        System.Threading.Tasks.Task<string> getPedidoAsync(string login, string passwd, string XML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hermespardini.com.br/b2b/apoio/schemas/HPWS.XMLServer.getPendenciaTecnica", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RastreabilidadeExame))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RastreabilidadeAmostra))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PendenciaTecnicaExame))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PendenciaTecnicaPedido))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Erro))]
        System.Threading.Tasks.Task<PardiniService.XMLPendenciaTecnica> getPendenciaTecnicaAsync(string login, string passwd, string dataInicial, string dataFinal, string horaInicial, string horaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hermespardini.com.br/b2b/apoio/schemas/HPWS.XMLServer.getRastreabilidade", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RastreabilidadeExame))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RastreabilidadeAmostra))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PendenciaTecnicaExame))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PendenciaTecnicaPedido))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Erro))]
        System.Threading.Tasks.Task<PardiniService.XMLRastreabilidade> getRastreabilidadeAsync(string login, string passwd, string dataInicial, string dataFinal, string horaInicial, string horaFinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hermespardini.com.br/b2b/apoio/schemas/HPWS.XMLServer.getResultado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RastreabilidadeExame))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RastreabilidadeAmostra))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PendenciaTecnicaExame))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PendenciaTecnicaPedido))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Erro))]
        System.Threading.Tasks.Task<string> getResultadoAsync(string login, string passwd, string XML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hermespardini.com.br/b2b/apoio/schemas/HPWS.XMLServer.getResultadoPedido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RastreabilidadeExame))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RastreabilidadeAmostra))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PendenciaTecnicaExame))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PendenciaTecnicaPedido))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Erro))]
        System.Threading.Tasks.Task<string> getResultadoPedidoAsync(string login, string passwd, long anoCodPedApoio, string CodPedApoio, string CodExmApoio, long PDF, long versaoResultado, bool papelTimbrado, long valorReferencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hermespardini.com.br/b2b/apoio/schemas/HPWS.XMLServer.getUltimoResultado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RastreabilidadeExame))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RastreabilidadeAmostra))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PendenciaTecnicaExame))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PendenciaTecnicaPedido))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Erro))]
        System.Threading.Tasks.Task<string> getUltimoResultadoAsync(string login, string passwd, string XML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hermespardini.com.br/b2b/apoio/schemas/HPWS.XMLServer.putInformacaoComplem" +
            "entar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RastreabilidadeExame))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RastreabilidadeAmostra))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PendenciaTecnicaExame))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PendenciaTecnicaPedido))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Erro))]
        System.Threading.Tasks.Task<string> putInformacaoComplementarAsync(string login, string passwd, string XML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://hermespardini.com.br/b2b/apoio/schemas/HPWS.XMLServer.verificarRecebimento" +
            "Pedido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RastreabilidadeExame))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RastreabilidadeAmostra))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PendenciaTecnicaExame))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PendenciaTecnicaPedido))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Erro))]
        System.Threading.Tasks.Task<string> verificarRecebimentoPedidoAsync(string login, string passwd, string ids, long unidade);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://hermespardini.com.br/b2b/apoio/schemas")]
    public partial class ListaErro
    {
        
        private Erro[] erroField;
        
        /// <remarks/>
        public Erro[] Erro
        {
            get
            {
                return this.erroField;
            }
            set
            {
                this.erroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://hermespardini.com.br/b2b/apoio/schemas")]
    public partial class Erro
    {
        
        private long codigoField;
        
        private bool codigoFieldSpecified;
        
        private string mensagemField;
        
        /// <remarks/>
        public long Codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool CodigoSpecified
        {
            get
            {
                return this.codigoFieldSpecified;
            }
            set
            {
                this.codigoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem
        {
            get
            {
                return this.mensagemField;
            }
            set
            {
                this.mensagemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://hermespardini.com.br/b2b/apoio/schemas")]
    public partial class RastreabilidadeExame
    {
        
        private string mnMaterialField;
        
        private string mnExameField;
        
        private string sqeExaField;
        
        private decimal codStatusField;
        
        private bool codStatusFieldSpecified;
        
        private string descricaoStatusField;
        
        private System.DateTime dataHoraStatusExameField;
        
        private bool dataHoraStatusExameFieldSpecified;
        
        /// <remarks/>
        public string mnMaterial
        {
            get
            {
                return this.mnMaterialField;
            }
            set
            {
                this.mnMaterialField = value;
            }
        }
        
        /// <remarks/>
        public string mnExame
        {
            get
            {
                return this.mnExameField;
            }
            set
            {
                this.mnExameField = value;
            }
        }
        
        /// <remarks/>
        public string sqeExa
        {
            get
            {
                return this.sqeExaField;
            }
            set
            {
                this.sqeExaField = value;
            }
        }
        
        /// <remarks/>
        public decimal codStatus
        {
            get
            {
                return this.codStatusField;
            }
            set
            {
                this.codStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool codStatusSpecified
        {
            get
            {
                return this.codStatusFieldSpecified;
            }
            set
            {
                this.codStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string descricaoStatus
        {
            get
            {
                return this.descricaoStatusField;
            }
            set
            {
                this.descricaoStatusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dataHoraStatusExame
        {
            get
            {
                return this.dataHoraStatusExameField;
            }
            set
            {
                this.dataHoraStatusExameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool dataHoraStatusExameSpecified
        {
            get
            {
                return this.dataHoraStatusExameFieldSpecified;
            }
            set
            {
                this.dataHoraStatusExameFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://hermespardini.com.br/b2b/apoio/schemas")]
    public partial class RastreabilidadeAmostra
    {
        
        private string unidadeField;
        
        private string pedidoField;
        
        private string amostraField;
        
        private string nomePacField;
        
        private string idtuboLabField;
        
        private string etqCodBarField;
        
        private string origemPedField;
        
        private System.DateTime dataHoraStatusAmostraField;
        
        private string codStatusField;
        
        private string descricaoStatusField;
        
        private string informacaoComplementarField;
        
        private RastreabilidadeExame[] examesField;
        
        private string retornoField;
        
        /// <remarks/>
        public string unidade
        {
            get
            {
                return this.unidadeField;
            }
            set
            {
                this.unidadeField = value;
            }
        }
        
        /// <remarks/>
        public string pedido
        {
            get
            {
                return this.pedidoField;
            }
            set
            {
                this.pedidoField = value;
            }
        }
        
        /// <remarks/>
        public string amostra
        {
            get
            {
                return this.amostraField;
            }
            set
            {
                this.amostraField = value;
            }
        }
        
        /// <remarks/>
        public string nomePac
        {
            get
            {
                return this.nomePacField;
            }
            set
            {
                this.nomePacField = value;
            }
        }
        
        /// <remarks/>
        public string idtuboLab
        {
            get
            {
                return this.idtuboLabField;
            }
            set
            {
                this.idtuboLabField = value;
            }
        }
        
        /// <remarks/>
        public string etqCodBar
        {
            get
            {
                return this.etqCodBarField;
            }
            set
            {
                this.etqCodBarField = value;
            }
        }
        
        /// <remarks/>
        public string origemPed
        {
            get
            {
                return this.origemPedField;
            }
            set
            {
                this.origemPedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dataHoraStatusAmostra
        {
            get
            {
                return this.dataHoraStatusAmostraField;
            }
            set
            {
                this.dataHoraStatusAmostraField = value;
            }
        }
        
        /// <remarks/>
        public string codStatus
        {
            get
            {
                return this.codStatusField;
            }
            set
            {
                this.codStatusField = value;
            }
        }
        
        /// <remarks/>
        public string descricaoStatus
        {
            get
            {
                return this.descricaoStatusField;
            }
            set
            {
                this.descricaoStatusField = value;
            }
        }
        
        /// <remarks/>
        public string informacaoComplementar
        {
            get
            {
                return this.informacaoComplementarField;
            }
            set
            {
                this.informacaoComplementarField = value;
            }
        }
        
        /// <remarks/>
        public RastreabilidadeExame[] exames
        {
            get
            {
                return this.examesField;
            }
            set
            {
                this.examesField = value;
            }
        }
        
        /// <remarks/>
        public string retorno
        {
            get
            {
                return this.retornoField;
            }
            set
            {
                this.retornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://hermespardini.com.br/b2b/apoio/schemas")]
    public partial class XMLRastreabilidade
    {
        
        private RastreabilidadeAmostra[] rastreabilidadeField;
        
        /// <remarks/>
        public RastreabilidadeAmostra[] Rastreabilidade
        {
            get
            {
                return this.rastreabilidadeField;
            }
            set
            {
                this.rastreabilidadeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://hermespardini.com.br/b2b/apoio/schemas")]
    public partial class PendenciaTecnicaExame
    {
        
        private string mnMaterialField;
        
        private string mnExameField;
        
        private string sqeExaField;
        
        private string observacaoDoExameField;
        
        private string disposicaoField;
        
        private string pendenciaField;
        
        private string detalhamentoPendenciaField;
        
        /// <remarks/>
        public string mnMaterial
        {
            get
            {
                return this.mnMaterialField;
            }
            set
            {
                this.mnMaterialField = value;
            }
        }
        
        /// <remarks/>
        public string mnExame
        {
            get
            {
                return this.mnExameField;
            }
            set
            {
                this.mnExameField = value;
            }
        }
        
        /// <remarks/>
        public string sqeExa
        {
            get
            {
                return this.sqeExaField;
            }
            set
            {
                this.sqeExaField = value;
            }
        }
        
        /// <remarks/>
        public string observacaoDoExame
        {
            get
            {
                return this.observacaoDoExameField;
            }
            set
            {
                this.observacaoDoExameField = value;
            }
        }
        
        /// <remarks/>
        public string disposicao
        {
            get
            {
                return this.disposicaoField;
            }
            set
            {
                this.disposicaoField = value;
            }
        }
        
        /// <remarks/>
        public string pendencia
        {
            get
            {
                return this.pendenciaField;
            }
            set
            {
                this.pendenciaField = value;
            }
        }
        
        /// <remarks/>
        public string detalhamentoPendencia
        {
            get
            {
                return this.detalhamentoPendenciaField;
            }
            set
            {
                this.detalhamentoPendenciaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://hermespardini.com.br/b2b/apoio/schemas")]
    public partial class PendenciaTecnicaPedido
    {
        
        private string codLabField;
        
        private string codPedApoioField;
        
        private string dataPedField;
        
        private string nomePacField;
        
        private string origemPedField;
        
        private string codPedLabField;
        
        private System.DateTime dataHoraInicialPendenciaField;
        
        private bool dataHoraInicialPendenciaFieldSpecified;
        
        private System.DateTime dataHoraFinalPendenciaField;
        
        private bool dataHoraFinalPendenciaFieldSpecified;
        
        private string situacaoPendenciaField;
        
        private PendenciaTecnicaExame[] examesField;
        
        private string observacaoPedidoField;
        
        private string retornoField;
        
        /// <remarks/>
        public string codLab
        {
            get
            {
                return this.codLabField;
            }
            set
            {
                this.codLabField = value;
            }
        }
        
        /// <remarks/>
        public string codPedApoio
        {
            get
            {
                return this.codPedApoioField;
            }
            set
            {
                this.codPedApoioField = value;
            }
        }
        
        /// <remarks/>
        public string dataPed
        {
            get
            {
                return this.dataPedField;
            }
            set
            {
                this.dataPedField = value;
            }
        }
        
        /// <remarks/>
        public string nomePac
        {
            get
            {
                return this.nomePacField;
            }
            set
            {
                this.nomePacField = value;
            }
        }
        
        /// <remarks/>
        public string origemPed
        {
            get
            {
                return this.origemPedField;
            }
            set
            {
                this.origemPedField = value;
            }
        }
        
        /// <remarks/>
        public string codPedLab
        {
            get
            {
                return this.codPedLabField;
            }
            set
            {
                this.codPedLabField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dataHoraInicialPendencia
        {
            get
            {
                return this.dataHoraInicialPendenciaField;
            }
            set
            {
                this.dataHoraInicialPendenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool dataHoraInicialPendenciaSpecified
        {
            get
            {
                return this.dataHoraInicialPendenciaFieldSpecified;
            }
            set
            {
                this.dataHoraInicialPendenciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dataHoraFinalPendencia
        {
            get
            {
                return this.dataHoraFinalPendenciaField;
            }
            set
            {
                this.dataHoraFinalPendenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool dataHoraFinalPendenciaSpecified
        {
            get
            {
                return this.dataHoraFinalPendenciaFieldSpecified;
            }
            set
            {
                this.dataHoraFinalPendenciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string situacaoPendencia
        {
            get
            {
                return this.situacaoPendenciaField;
            }
            set
            {
                this.situacaoPendenciaField = value;
            }
        }
        
        /// <remarks/>
        public PendenciaTecnicaExame[] exames
        {
            get
            {
                return this.examesField;
            }
            set
            {
                this.examesField = value;
            }
        }
        
        /// <remarks/>
        public string observacaoPedido
        {
            get
            {
                return this.observacaoPedidoField;
            }
            set
            {
                this.observacaoPedidoField = value;
            }
        }
        
        /// <remarks/>
        public string retorno
        {
            get
            {
                return this.retornoField;
            }
            set
            {
                this.retornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://hermespardini.com.br/b2b/apoio/schemas")]
    public partial class XMLPendenciaTecnica
    {
        
        private PendenciaTecnicaPedido[] pendenciasTecnicasField;
        
        /// <remarks/>
        public PendenciaTecnicaPedido[] PendenciasTecnicas
        {
            get
            {
                return this.pendenciasTecnicasField;
            }
            set
            {
                this.pendenciasTecnicasField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface XMLServerSoapChannel : PardiniService.XMLServerSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class XMLServerSoapClient : System.ServiceModel.ClientBase<PardiniService.XMLServerSoap>, PardiniService.XMLServerSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public XMLServerSoapClient() : 
                base(XMLServerSoapClient.GetDefaultBinding(), XMLServerSoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.XMLServerSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XMLServerSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(XMLServerSoapClient.GetBindingForEndpoint(endpointConfiguration), XMLServerSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XMLServerSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(XMLServerSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XMLServerSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(XMLServerSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XMLServerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> cancelaAmostraAsync(string login, string passwd, string idTuboLab)
        {
            return base.Channel.cancelaAmostraAsync(login, passwd, idTuboLab);
        }
        
        public System.Threading.Tasks.Task<string> cancelaExameAsync(string login, string passwd, string codPedApoio, string codExmApoio)
        {
            return base.Channel.cancelaExameAsync(login, passwd, codPedApoio, codExmApoio);
        }
        
        public System.Threading.Tasks.Task<string> getGrupoFracionamentoAsync(string login, string passwd, long examesVeterinarios)
        {
            return base.Channel.getGrupoFracionamentoAsync(login, passwd, examesVeterinarios);
        }
        
        public System.Threading.Tasks.Task<PardiniService.ListaErro> getListaErroPedidoAsync(string login, string passwd)
        {
            return base.Channel.getListaErroPedidoAsync(login, passwd);
        }
        
        public System.Threading.Tasks.Task<string> getPedidoAsync(string login, string passwd, string XML)
        {
            return base.Channel.getPedidoAsync(login, passwd, XML);
        }
        
        public System.Threading.Tasks.Task<PardiniService.XMLPendenciaTecnica> getPendenciaTecnicaAsync(string login, string passwd, string dataInicial, string dataFinal, string horaInicial, string horaFinal)
        {
            return base.Channel.getPendenciaTecnicaAsync(login, passwd, dataInicial, dataFinal, horaInicial, horaFinal);
        }
        
        public System.Threading.Tasks.Task<PardiniService.XMLRastreabilidade> getRastreabilidadeAsync(string login, string passwd, string dataInicial, string dataFinal, string horaInicial, string horaFinal)
        {
            return base.Channel.getRastreabilidadeAsync(login, passwd, dataInicial, dataFinal, horaInicial, horaFinal);
        }
        
        public System.Threading.Tasks.Task<string> getResultadoAsync(string login, string passwd, string XML)
        {
            return base.Channel.getResultadoAsync(login, passwd, XML);
        }
        
        public System.Threading.Tasks.Task<string> getResultadoPedidoAsync(string login, string passwd, long anoCodPedApoio, string CodPedApoio, string CodExmApoio, long PDF, long versaoResultado, bool papelTimbrado, long valorReferencia)
        {
            return base.Channel.getResultadoPedidoAsync(login, passwd, anoCodPedApoio, CodPedApoio, CodExmApoio, PDF, versaoResultado, papelTimbrado, valorReferencia);
        }
        
        public System.Threading.Tasks.Task<string> getUltimoResultadoAsync(string login, string passwd, string XML)
        {
            return base.Channel.getUltimoResultadoAsync(login, passwd, XML);
        }
        
        public System.Threading.Tasks.Task<string> putInformacaoComplementarAsync(string login, string passwd, string XML)
        {
            return base.Channel.putInformacaoComplementarAsync(login, passwd, XML);
        }
        
        public System.Threading.Tasks.Task<string> verificarRecebimentoPedidoAsync(string login, string passwd, string ids, long unidade)
        {
            return base.Channel.verificarRecebimentoPedidoAsync(login, passwd, ids, unidade);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.XMLServerSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.XMLServerSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://www.hermespardini.com.br/b2b/HPWS.XMLServer.cls");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return XMLServerSoapClient.GetBindingForEndpoint(EndpointConfiguration.XMLServerSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return XMLServerSoapClient.GetEndpointAddress(EndpointConfiguration.XMLServerSoap);
        }
        
        public enum EndpointConfiguration
        {
            
            XMLServerSoap,
        }
    }
}
