//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace ApiIntegracaoEntity.Pardini {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Registro {
        
        private short protocoloField;
        
        private string idField;
        
        private RegistroLote loteField;
        
        /// <remarks/>
        public short Protocolo {
            get {
                return this.protocoloField;
            }
            set {
                this.protocoloField = value;
            }
        }
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public RegistroLote Lote {
            get {
                return this.loteField;
            }
            set {
                this.loteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RegistroLote {
        
        private string codLabField;
        
        private string codLoteLabField;
        
        private int contratoField;
        
        private bool contratoFieldSpecified;
        
        private System.DateTime dataLoteField;
        
        private System.DateTime horaLoteField;
        
        private RegistroLotePedido[] pedidoField;
        
        /// <remarks/>
        public string CodLab {
            get {
                return this.codLabField;
            }
            set {
                this.codLabField = value;
            }
        }
        
        /// <remarks/>
        public string CodLoteLab {
            get {
                return this.codLoteLabField;
            }
            set {
                this.codLoteLabField = value;
            }
        }
        
        /// <remarks/>
        public int Contrato {
            get {
                return this.contratoField;
            }
            set {
                this.contratoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ContratoSpecified {
            get {
                return this.contratoFieldSpecified;
            }
            set {
                this.contratoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DataLote {
            get {
                return this.dataLoteField;
            }
            set {
                this.dataLoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime HoraLote {
            get {
                return this.horaLoteField;
            }
            set {
                this.horaLoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Pedido")]
        public RegistroLotePedido[] Pedido {
            get {
                return this.pedidoField;
            }
            set {
                this.pedidoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RegistroLotePedido {
        
        private string codPedLabField;
        
        private System.DateTime dataPedField;
        
        private bool dataPedFieldSpecified;
        
        private System.DateTime horaPedField;
        
        private bool horaPedFieldSpecified;
        
        private System.DateTime dataUltMensField;
        
        private bool dataUltMensFieldSpecified;
        
        private string obsField;
        
        private RegistroLotePedidoPaciente pacienteField;
        
        private RegistroLotePedidoMedico[] medicoField;
        
        private RegistroLotePedidoExame[] exameField;
        
        /// <remarks/>
        public string CodPedLab {
            get {
                return this.codPedLabField;
            }
            set {
                this.codPedLabField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DataPed {
            get {
                return this.dataPedField;
            }
            set {
                this.dataPedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataPedSpecified {
            get {
                return this.dataPedFieldSpecified;
            }
            set {
                this.dataPedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime HoraPed {
            get {
                return this.horaPedField;
            }
            set {
                this.horaPedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HoraPedSpecified {
            get {
                return this.horaPedFieldSpecified;
            }
            set {
                this.horaPedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DataUltMens {
            get {
                return this.dataUltMensField;
            }
            set {
                this.dataUltMensField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataUltMensSpecified {
            get {
                return this.dataUltMensFieldSpecified;
            }
            set {
                this.dataUltMensFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Obs {
            get {
                return this.obsField;
            }
            set {
                this.obsField = value;
            }
        }
        
        /// <remarks/>
        public RegistroLotePedidoPaciente Paciente {
            get {
                return this.pacienteField;
            }
            set {
                this.pacienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Medico")]
        public RegistroLotePedidoMedico[] Medico {
            get {
                return this.medicoField;
            }
            set {
                this.medicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Exame")]
        public RegistroLotePedidoExame[] Exame {
            get {
                return this.exameField;
            }
            set {
                this.exameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RegistroLotePedidoPaciente {
        
        private string codPacLabField;
        
        private string nomeField;
        
        private string sexoField;
        
        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private string cPFField;
        
        /// <remarks/>
        public string CodPacLab {
            get {
                return this.codPacLabField;
            }
            set {
                this.codPacLabField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DataNasc", typeof(System.DateTime), DataType="date")]
        [System.Xml.Serialization.XmlElementAttribute("IdadeAno", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("IdadeDia", typeof(int))]
        [System.Xml.Serialization.XmlElementAttribute("IdadeMes", typeof(int))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        public string CPF {
            get {
                return this.cPFField;
            }
            set {
                this.cPFField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        DataNasc,
        
        /// <remarks/>
        IdadeAno,
        
        /// <remarks/>
        IdadeDia,
        
        /// <remarks/>
        IdadeMes,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RegistroLotePedidoMedico {
        
        private RegistroLotePedidoMedicoSiglaConselho siglaConselhoField;
        
        private bool siglaConselhoFieldSpecified;
        
        private RegistroLotePedidoMedicoUfConselho ufConselhoField;
        
        private bool ufConselhoFieldSpecified;
        
        private string numeroConselhoField;
        
        private string nomeField;
        
        private long seqmedField;
        
        /// <remarks/>
        public RegistroLotePedidoMedicoSiglaConselho siglaConselho {
            get {
                return this.siglaConselhoField;
            }
            set {
                this.siglaConselhoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool siglaConselhoSpecified {
            get {
                return this.siglaConselhoFieldSpecified;
            }
            set {
                this.siglaConselhoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public RegistroLotePedidoMedicoUfConselho ufConselho {
            get {
                return this.ufConselhoField;
            }
            set {
                this.ufConselhoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ufConselhoSpecified {
            get {
                return this.ufConselhoFieldSpecified;
            }
            set {
                this.ufConselhoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string numeroConselho {
            get {
                return this.numeroConselhoField;
            }
            set {
                this.numeroConselhoField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public long seqmed {
            get {
                return this.seqmedField;
            }
            set {
                this.seqmedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum RegistroLotePedidoMedicoSiglaConselho {
        
        /// <remarks/>
        CRAS,
        
        /// <remarks/>
        COREN,
        
        /// <remarks/>
        CRF,
        
        /// <remarks/>
        CREFITO,
        
        /// <remarks/>
        CRM,
        
        /// <remarks/>
        CRN,
        
        /// <remarks/>
        CRO,
        
        /// <remarks/>
        CRP,
        
        /// <remarks/>
        OUT,
        
        /// <remarks/>
        CRFA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum RegistroLotePedidoMedicoUfConselho {
        
        /// <remarks/>
        RS,
        
        /// <remarks/>
        SC,
        
        /// <remarks/>
        PR,
        
        /// <remarks/>
        SP,
        
        /// <remarks/>
        MG,
        
        /// <remarks/>
        RJ,
        
        /// <remarks/>
        ES,
        
        /// <remarks/>
        MS,
        
        /// <remarks/>
        MT,
        
        /// <remarks/>
        GO,
        
        /// <remarks/>
        TO,
        
        /// <remarks/>
        PA,
        
        /// <remarks/>
        AM,
        
        /// <remarks/>
        RO,
        
        /// <remarks/>
        RR,
        
        /// <remarks/>
        AC,
        
        /// <remarks/>
        DF,
        
        /// <remarks/>
        BA,
        
        /// <remarks/>
        SE,
        
        /// <remarks/>
        CE,
        
        /// <remarks/>
        PI,
        
        /// <remarks/>
        PB,
        
        /// <remarks/>
        RN,
        
        /// <remarks/>
        AL,
        
        /// <remarks/>
        MA,
        
        /// <remarks/>
        PE,
        
        /// <remarks/>
        AP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RegistroLotePedidoExame {
        
        private string itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        private string codExmLabField;
        
        private string descMatField;
        
        private short tempoField;
        
        private bool tempoFieldSpecified;
        
        private string condicaoField;
        
        private System.DateTime dataColetaField;
        
        private System.DateTime horaColetaField;
        
        private string observacaoField;
        
        private float dosagemField;
        
        private bool dosagemFieldSpecified;
        
        private string conservanteField;
        
        private RegistroLotePedidoExameInformacaoComplementar[] informacaoComplementarField;
        
        private long[] idMedicoSolicitanteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CodExmAMB", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("CodExmApoio", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("CodExmCBHPM", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("CodExmTUSS", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        public string CodExmLab {
            get {
                return this.codExmLabField;
            }
            set {
                this.codExmLabField = value;
            }
        }
        
        /// <remarks/>
        public string DescMat {
            get {
                return this.descMatField;
            }
            set {
                this.descMatField = value;
            }
        }
        
        /// <remarks/>
        public short Tempo {
            get {
                return this.tempoField;
            }
            set {
                this.tempoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TempoSpecified {
            get {
                return this.tempoFieldSpecified;
            }
            set {
                this.tempoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Condicao {
            get {
                return this.condicaoField;
            }
            set {
                this.condicaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DataColeta {
            get {
                return this.dataColetaField;
            }
            set {
                this.dataColetaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
        public System.DateTime HoraColeta {
            get {
                return this.horaColetaField;
            }
            set {
                this.horaColetaField = value;
            }
        }
        
        /// <remarks/>
        public string Observacao {
            get {
                return this.observacaoField;
            }
            set {
                this.observacaoField = value;
            }
        }
        
        /// <remarks/>
        public float Dosagem {
            get {
                return this.dosagemField;
            }
            set {
                this.dosagemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DosagemSpecified {
            get {
                return this.dosagemFieldSpecified;
            }
            set {
                this.dosagemFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Conservante {
            get {
                return this.conservanteField;
            }
            set {
                this.conservanteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InformacaoComplementar")]
        public RegistroLotePedidoExameInformacaoComplementar[] InformacaoComplementar {
            get {
                return this.informacaoComplementarField;
            }
            set {
                this.informacaoComplementarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("idMedicoSolicitante")]
        public long[] idMedicoSolicitante {
            get {
                return this.idMedicoSolicitanteField;
            }
            set {
                this.idMedicoSolicitanteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        CodExmAMB,
        
        /// <remarks/>
        CodExmApoio,
        
        /// <remarks/>
        CodExmCBHPM,
        
        /// <remarks/>
        CodExmTUSS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class RegistroLotePedidoExameInformacaoComplementar {
        
        private string infoCompField;
        
        private string valorField;
        
        /// <remarks/>
        public string InfoComp {
            get {
                return this.infoCompField;
            }
            set {
                this.infoCompField = value;
            }
        }
        
        /// <remarks/>
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
}
